 # como render es gratis y se apaga por inactividad esto  manda ping  para que  no se apague en caso de querer revisar profe 
name: Keep Render Alive
on:
  schedule:
    - cron: "*/5 * * * *"   # cada 5 minutos
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping root URL
        run: curl -fsS --max-time 15 "${{ secrets.RENDER_URL }}" || true
